### ISSUE TITLE
webview 背景是白色不是透明的，在bmCharts部分，一直是背景是白色，无法透明

### ISSUE THREAD

**Issue by shenmashi** [bmfe/WeexSDK#1]
需要修改代码
WeexSDK /src/main/java/com/taobao/weex/ui/view/WXWebView.java
65行修改为   root.setBackgroundColor(Color.TRANSPARENT);
73行添加  mWebView.setBackgroundColor(0);
即可

**Comment by myliuyx** [comment]
已经添加~
